### PR TITLE
Links added and updated

### PR DESCRIPTION
**Pull request by SatjaSivcev**
README links updated and fixed.

### CODE REVIEW

**Comment by SatjaSivcev** [comment]
I agree relative links are the way to go. Can you give one example?

**Comment by knatten** [comment]
They need to be relative to the document. So for instance this should work:

```markdown
[**CaptureHDRCompleteSettings**](CaptureHDRCompleteSettings/CaptureHDRCompleteSettings/CaptureHDRCompleteSettings.cs) 
```

You can read more about it in the article I linked.

**Comment by SatjaSivcev** [comment]
I have made the changes.

**Comment by knatten** [comment]
Nice! I would prefer if you squashed the two commits so we don't have an intermediary commit with absolute links. I can show you how if you want.

**Comment by SatjaSivcev** [comment]
Relative links don't work from Confluence page so we need to keep them full pointing to the master.

**Comment by SatjaSivcev** [comment]
Squashed commits. Ready for the next round. I suggest we merge without fixing links. Leave them absolute for now and make an issue.

**Comment by knatten** [comment]
Agreed. I suggest keeping just one issue to fix all the repos: https://github.com/zivid/cpp-extra-samples/issues/8

**Pull request merged**
